
jobs:
 build:
   docker:
     - image: cimg/python:3.8
   steps:
     - checkout
     - run: echo "🔧 Building the application..."

 test:
   docker:
     - image: cimg/python:3.8
   steps:
     - run: echo "🧪 Running tests..."

 deploy:
   docker:
     - image: cimg/python:3.8
   steps:
     - run: echo "🚀 Deploying the application..."


workflows:
 version: 2
 build-test-deploy:
   jobs:
     - build
     - test:
         requires:
           - build
     - deploy:
         requires:
           - test
