version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - checkout
      - run: echo "Building..."
  test:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - run: echo "Testing..."
workflows:
  my-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
